# Setup
title:            Programa Contexto
tagline:          Programa contexto
url:              http://javierarques.github.io/contexto/
respository:      javierarques/contexto

# Permalinks
permalink:        /:title



# Server
source:           ./src
destination:      ./_site
host:             0.0.0.0
port:             9001
baseurl:          ""
encoding:         UTF-8
exclude:         ["node_modules", "vendor"]


# Dependencies
markdown:         kramdown
highlighter:      rouge

# Assets
sass:
  sass_dir:          _scss
  style:            :compressed

# Gem dependencies
gems:
  - octopress-autoprefixer
