---
title: Programa Contexto
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  members:
    title: members
    output: false
  researchers:
    title: researchers
    output: false
description: Programa de Investigación, Formación, Intervención y Prevención de la Violencia de Género a través del trabajo con el agresor
tagline: Programa de Investigación, Formación, Intervención y Prevención de la Violencia de Género a través del trabajo con el agresor
url: "https://www.programacontexto.org"
respository: javierarques/contexto
permalink: "/:title"
source: "./src"
destination: "./_site"
host: 0.0.0.0
port: 9001
baseurl: ''
encoding: UTF-8
exclude:
- node_modules
- vendor
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _scss
  style: :compressed
plugins:
  - octopress-autoprefixer
  - jekyll-sitemap
