# Setup
title:               Programa Contexto
tagline:             Programa contexto
url:                 http://javierarques.github.io/contexto/
permalink:           /:title
baseurl:             /contexto
respository:         javierarques/contexto
port: 3000
lsi: false
markdown: kramdown

# Assets
sass:
  sass_dir:          _scss
  style:            :compressed
